name: mcg76_TNTRun
version: 1.5.0
api: 1.8.0
main: mcg76\game\tntrun\TNTRunPlugin
author: minecraftgenius76
description: minecraftgenius76 Minigame TNT_Run Experimental build 
commands:
 tntrun:
  description: "Start minecraftgenius76 Minigame TNT Run Experimental Build"
  permission: mcg76.tntrun
permissions:
 mcg76.plugin.tntrun:
  description: "mcg76.tntrun"
  default: true